name: Add markdown created time
run-name: Add markdown created time
on: [push]
jobs:
  update-md:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Modified Markdown Files
        id: get_files
        run: |
          modified_files=$(git diff --name-only "HEAD^" | grep ".md$") || true
          echo "files=$modified_files" >> $GITHUB_OUTPUT

      - name: Insert Front Matter
        run: |
          IFS=`echo -e "\n"`
          files="${{ steps.get_files.outputs.files }}"
          for file in $files; do
            if [[ -f "$file" ]]; then
              echo "Processing [$file]..."
              filename=$(basename "$file" .md)
              front_matter=$(head -n 3 "$file")
              if [[ "$front_matter" = "---"* ]]; then
                echo 'Skip insert Front Matter'
                # sed -i "s/^---\ntitle: $filename\ndate: .*/---\ntitle: $filename\ndate: $(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")/" "$file"
              else
                echo 'Insert Front Matter'
                sed -i "1i---\ntitle: $filename\ndate: $(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")\n---\n" "$file"
              fi
            else
              echo "文件 $file 不存在"
            fi
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Markdown files with front matter
